[appendix]

[[ruby-on-rails-install-how-to]]
= Ruby on Rails Install How-to

[[development-system]]
== Development System

This chapter's installation methods described are intended for
development systems. If you are looking for instructions on installing a
web server in the production system, please have a look at the chapter
which handles the server setup.

Both types of installation are very different.

[[ruby-on-rails-5.0-on-debian-8.3-jessie]]
== Ruby on Rails 5.0 on Debian 8.3 (Jessie)

((("Debian", "8.3 (Jessie)")))
There are two main reasons for installing a Ruby on Rails system with
RVM (Ruby Version Manager):

* You simply do not have any root rights on the system. In that case,
you have no other option.
* You want to run several Rails systems that are separated cleanly, and
perhaps also separate Ruby versions. This can be easily done with RVM.
You can run Ruby 1.9.3 with Rails 3.2 and in parallel Ruby 2.3.0 with
Rails 5.0.

NOTE: Detailed information on RVM can be found on the
      RVM homepage at https://rvm.io

This description assumes that you have a freshly installed Debian
GNU/Linux 8.3 ("Jessie"). You will find an ISO image for the
installation at http://www.debian.org. I recommend the approximately 250
MB net installation CD image. For instructions on how to install
Debian-GNU/Linux, please go to http://www.debian.org/distrib/netinst.

[[preparations]]
=== Preparations

If you have root rights on the target system, you can use the following
commands to ensure that all required programs for a successful
installation of RVM are available. If you do not have root rights, you
have to either hope that your admin has already installed everything you
need, or send them a quick e-mail with the corresponding lines.

Login as root and update the package lists:

[subs="quotes"]
----
root@debian:~# **apt-get update**
[...]
root@debian:~#
----

[NOTE]
====
Of course, you can optionally install a SSH server on the system, so you
can work on the system via SSH instead of on the console:

[subs="quotes"]
----
root@debian:~# **apt-get -y install openssh-server**
----
====

And now the installation of the packages required for the RVM
installation:

[subs="quotes"]
----
root@debian:~# **apt-get -y install curl patch bzip2 \
gawk g++ gcc make libc6-dev patch libreadline6-dev \
zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev \
sqlite3 autoconf libgdbm-dev libncurses5-dev \
automake libtool bison pkg-config libffi-dev nodejs**
[...]
root@debian:~#
----

Now is a good time to log out as root:

[subs="quotes"]
----
root@debian:~# **exit**
logout
xyz@debian:~$
----

[[installing-ruby-2.3-and-ruby-on-rails-5.0-with-rvm]]
=== Installing Ruby 2.3 and Ruby on Rails 5.0 with RVM

((("RVM")))
Log in with your normal user account (in our case, it's the user `xyz`).

RVM, Ruby, and Ruby on Rails can be installed in various ways. I
recommend using the following commands and get at least one cup of
tea/coffee/favorite drink:

[subs="quotes"]
----
xyz@debian:~$ **gpg --keyserver hkp://keys.gnupg.net \
--recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3**
[...]
xyz@debian:~$ **curl -sSL https://get.rvm.io | bash**
[...]
xyz@debian:~$ **source /home/xyz/.rvm/scripts/rvm**
xyz@debian:~$ **rvm install 2.3 --autolibs=read-only**
[...]
xyz@debian:~$ **gem install**
[...]
xyz@debian:~$
----

NOTE: `gem install rails` installs the current stable Rails version.
      You can use the format `gem install rails -v 5.0.0` to install
      a specific version and `gem install rails --pre` to install a
      current beta version.

RVM, Ruby 2.3 and Rails 5.0 are now installed. You can check it
with the following commands.

[subs="quotes"]
----
xyz@debian:~$ **ruby -v**
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
xyz@debian:~$ **rails -v**
Rails 5.0.0
xyz@debian:~$
----

[[ruby-on-rails-5.0-on-windows]]
== Ruby on Rails 5.0 on Windows

((("Windows")))
At http://railsinstaller.org/ there is a simple, all-inclusive Ruby on
Rails installer for Windows for Ruby and Rails.

[[ruby-on-rails-5.0-on-mac-os-x-10.11-el-capitan]]
== Ruby on Rails 5.0 on Mac OS X 10.11 (El Capitan)

((("Mac OS X", "10.11 (El Capitan)")))
Mac OS 10.11 includes Ruby by default. Not interesting for our purposes.
We want Ruby 2.3 and Rails 5.0. To avoid interfering with the existing
Ruby and Rails installation and therefore the packet management of Mac
OS X, we install Ruby 2.3 and Rails 5.0 with RVM (Ruby Version Manager).

With RVM, you can install and run any number of Ruby and Rails versions
as normal user (without root rights and in your home directory). So you
can work in parallel on old projects that may still use Ruby 1.9.3 and
new projects that use Ruby 2.3.

NOTE: Detailed information on RVM can be found at the RVM
      homepage at https://rvm.io/

[[xcode-installation-or-upgrade]]
=== Xcode Installation or Upgrade

Before you start installing Ruby on Rails, you must install the _latest_
Apple Xcode tools on your system. The easiest way is via the Mac App
Store (search for "xcode") or via the website
https://developer.apple.com/xcode/

Please take care to install all the command line tools!

[[installing-ruby-2.3-and-ruby-on-rails-5.0-with-rvm-1]]
=== Installing Ruby 2.3 and Ruby on Rails 5.0 with RVM

RVM can be installed in various ways. I recommend using the following
monster command (please copy it exactly) that installs the latest RVM,
Ruby and Ruby on Rails in your home directory:

[subs="quotes"]
----
$ **gpg --keyserver hkp://keys.gnupg.net \
--recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3**
[...]
$ **curl -sSL https://get.rvm.io | bash**
[...]
$
----

Now exit the current shell/terminal and open a new one for the next
commands.

[subs="quotes"]
----
$ **rvm install 2.3**
[...]
$ **gem install rails**
[...]
$
----

NOTE: `gem install rails` installs the current stable Rails version.
      You can use the format `gem install rails -v 5.0.0` to install
      a specific version and `gem install rails --pre` to install a
      current beta version.

RVM, Ruby 2.3 and Rails 5.0 are now fully installed. You can check it
with the following commands.

[subs="quotes"]
----
$ **ruby -v**
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
$ **rails -v**
Rails 5.0.0
$
----
